language: go
sudo: false

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - top

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v ./...
  - goveralls -service=travis-ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
